# Generated by Django 5.2.3 on 2025-06-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
    ]
